[package]
name = "cefrust"
version = "0.1.0"
authors = ["Guillermo Zunino <guillez@gmail.com>"]
build = "build.rs"

[build-dependencies.libbindgen]
git = "https://github.com/servo/rust-bindgen"
#features = ["llvm_stable"]

[dependencies]
x11 = "2.12.0"
